all_joints:
- - 0
- - 1
- - 2
all_joints_names:
- Tete
- Corps
- Queue
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
contrast:
  clahe: true
  claheratio: 0.1
  histeq: true
  histeqratio: 0.1
convolution:
  edge: false
  emboss:
    alpha:
    - 0.0
    - 1.0
    strength:
    - 0.5
    - 1.5
  embossratio: 0.1
  sharpen: false
  sharpenratio: 0.3
cropratio: 0.4
dataset: training-datasets\iteration-0\UnaugmentedDataSet_open_field_zoneJul11\open_field_zone_Me95shuffle1.mat
dataset_type: albumentations
decay_steps: 30000
display_iters: 1000
engine: pytorch
global_scale: 0.8
init_weights: c:\Users\schiv\anaconda3\envs\DEEPLABCUT\lib\site-packages\deeplabcut
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets\iteration-0\UnaugmentedDataSet_open_field_zoneJul11\Documentation_data-open_field_zone_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: hrnet_w48
num_joints: 3
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: C:\Users\schiv\OneDrive\Desktop\Cours\Master\GSON\Stage_M1\Travail\Scripts\open_field_model\open_field_zone-Me-2024-07-11
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
